# Generated by Django 5.2.6 on 2025-09-14 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(help_text="Título do jogo", max_length=100)),
                ("rating", models.IntegerField(help_text="Nota de 1 a 10")),
                (
                    "comment",
                    models.TextField(
                        help_text="Comentário sobre o jogo", max_length=500
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data de criação"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuário que criou a avaliação",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
