# Generated by Django 5.2.6 on 2025-09-28 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Games", "0001_initial"),
        ("Reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="title",
        ),
        migrations.AddField(
            model_name="review",
            name="game",
            field=models.ForeignKey(
                default=None,
                help_text="Jogo que está sendo avaliado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="Games.gamesmodel",
            ),
        ),
    ]
