# Generated by Django 5.2.6 on 2025-09-28 19:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Games", "0002_gamesmodel_reviews_fk"),
        ("Reviews", "0002_remove_review_title_review_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "game")},
        ),
    ]
