# Generated by Django 5.2.6 on 2025-09-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GamesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(help_text="Título do jogo", max_length=100)),
                (
                    "platforms",
                    models.CharField(
                        help_text="Plataformas suportadas", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Descrição do jogo", max_length=500),
                ),
                ("release_date", models.DateField(help_text="Data de lançamento")),
                (
                    "developer",
                    models.CharField(
                        help_text="Desenvolvedora do jogo", max_length=100
                    ),
                ),
            ],
        ),
    ]
