# Generated by Django 5.2.6 on 2025-09-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Games", "0001_initial"),
        ("Reviews", "0002_remove_review_title_review_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesmodel",
            name="reviews_fk",
            field=models.ManyToManyField(
                blank=True,
                help_text="Avaliações do jogo",
                related_name="games",
                to="Reviews.review",
            ),
        ),
    ]
