# Generated by Django 5.2.6 on 2025-09-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Games", "0002_gamesmodel_reviews_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamesmodel",
            name="reviews_fk",
        ),
    ]
